<?php
    $default_attribs = [
        'id'                   => [],
        'class'                => [],
        'title'                => [],
        'style'                => [],
        'href'                 => [],
        'target'               => [
            '_blank',
        ],
        'colspan'              => [],
        'rowspan'              => [],
        'aria-checked'         => [],
        'aria-controls'        => [],
        'aria-disabled'        => [],
        'aria-expanded'        => [],
        'aria-hidden'          => [],
        'aria-label'           => [],
        'aria-selected'        => [],
        'data-open-first-item' => [],
        'data-target'          => [],
    ];

    $allowed_html = [
        'h2'     => $default_attribs,
        'h3'     => $default_attribs,
        'div'    => $default_attribs,
        'span'   => $default_attribs,
        'p'      => $default_attribs,
        'a'      => $default_attribs,
        'button' => $default_attribs,
        'br'     => $default_attribs,
        'strong' => $default_attribs,
        'b'      => $default_attribs,
        'i'      => $default_attribs,
        'em'     => $default_attribs,
        'ul'     => $default_attribs,
        'ol'     => $default_attribs,
        'li'     => $default_attribs,
        'table'  => $default_attribs,
        'thead'  => $default_attribs,
        'tbody'  => $default_attribs,
        'th'     => $default_attribs,
        'tr'     => $default_attribs,
        'td'     => $default_attribs,
    ];
